### ISSUE TITLE
CSS: `a-input` selects with multiple entries are truncated

### ISSUE THREAD

**Issue by nathanaelhoun** [tdelavoux/Atom#4]
Because `.a-input` are `overflow: hidden`'ed, some options in a `<select multiple>` can be hidden, and there is no scrollbar to have them accessible.

| Current | Expected |
| :- | -: |
| ![image](https://user-images.githubusercontent.com/45119518/172848011-1374f9ce-e146-4c04-891a-acae0b492df5.png)| ![image](https://user-images.githubusercontent.com/45119518/172848138-0ae7a03b-503f-408e-a3b1-101d2a116bc9.png)|

**Comment by tdelavoux** [comment]
Fixed in [52c2c78]. 
Multiples elements are not affected by overflow: hidden.
