### ISSUE TITLE
FonAwesome content unreadable

### ISSUE THREAD

**Issue by tdelavoux** [tdelavoux/Atom#6]
@nathanaelhoun on the scss files, all contents for Font awesome 6 lost the backslash and are now considered as text and not a font. 
Before i fix the backslash, was it a voluntary change to include font awsome scss files in atom build ?

![image](https://user-images.githubusercontent.com/31383617/173242307-bc2a9dac-9a7f-4cca-9909-ed0569001b19.png)

**Comment by nathanaelhoun** [comment]
![image](https://user-images.githubusercontent.com/45119518/173327833-a4482e3d-596c-45e7-8e2b-427ca86f066a.png)

It was not intended. I'll spin up a PR in a sec.
